#!/usr/bin/env php

<?php

use Minicli\App;
use Minicli\Curly\Client;
use Minicli\Exception\CommandNotFoundException;

if (php_sapi_name() !== 'cli') {
    exit;
}

$vendor_path = __DIR__ . '/vendor/autoload.php';

if (!file_exists($vendor_path)) {
    $minicli_home = getenv('MINICLI_HOME') ?: '/usr/share/minicli';
    $vendor_path = $minicli_home . '/vendor/autoload.php';
}

require $vendor_path;

$app = new App(['debug' => true]);

$app->setSignature('Usage: ./minicli advice');

$app->registerCommand('advice', function () use ($app) {
    $client = new Client();

    $response = $client->get('https://api.adviceslip.com/advice');
    if ($response['code'] !== 200) {
        $app->getPrinter()->error('An API error has occurred.');
        return;
    }

    $advice = json_decode($response['body'], true);
    $app->getPrinter()->info($advice['slip']['advice']);
});

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->getPrinter()->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->getPrinter()->error("An error occurred:");
        $app->getPrinter()->error($exception->getMessage());
    }
    return 1;
}

return 0;